//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ejercicios_ASPnet {
	
	
	public partial class Formulario_web13 {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected System.Web.UI.WebControls.Content Content2;
		
		protected System.Web.UI.WebControls.RadioButton Suma;
		
		protected System.Web.UI.WebControls.RadioButton Resta;
		
		protected System.Web.UI.WebControls.TextBox Val1;
		
		protected System.Web.UI.WebControls.TextBox Val2;
		
		protected System.Web.UI.WebControls.TextBox Val3;
		
		protected System.Web.UI.WebControls.TextBox Val4;
		
		protected System.Web.UI.WebControls.TextBox Fecha1;
		
		protected System.Web.UI.WebControls.TextBox Fecha2;
		
		protected System.Web.UI.WebControls.Button ButtonCalcular;
		
		protected System.Web.UI.WebControls.Label Result;
	}
}
